#!/bin/bash

wget "$1" \
  --header 'authority: learn.fmi.uni-sofia.bg' \
  --header 'cache-control: max-age=0' \
  --header 'sec-ch-ua: "Microsoft Edge";v="95", "Chromium";v="95", ";Not A Brand";v="99"' \
  --header 'sec-ch-ua-mobile: ?0' \
  --header 'sec-ch-ua-platform: "Linux"' \
  --header 'dnt: 1' \
  --header 'upgrade-insecure-requests: 1' \
  --header 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.40 Safari/537.36 Edg/95.0.1020.20' \
  --header 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  --header 'sec-fetch-site: same-origin' \
  --header 'sec-fetch-mode: navigate' \
  --header 'sec-fetch-user: ?1' \
  --header 'sec-fetch-dest: document' \
  --header 'referer: https://learn.fmi.uni-sofia.bg/login/index.php' \
  --header 'accept-language: en-US,en;q=0.9' \
  --header 'cookie: MoodleSession=376d6e0ba0e57b73ff92bd37f8b4aab2' \

